### ISSUE TITLE
Issue with install via SNAPPY

### ISSUE THREAD

**Issue by cmbailey87** [3-manifolds/knot_floer_homology#9]
when I run for pythong version 3.5
pip3 install snappy  

I get the following for the knot_floer_homology library

     File "/tmp/pip-build-1g3q6faz/knot-floer-homology/setup.py", line 59, in <module>
         long_description=open('README.rst').read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 64: ordinal not in range(128)
    
   Please assist :)
   much thansk

**Comment by NathanDunfield** [comment]
Unfortunately, we only support Python 3.6 and newer (3.5 reached the end of its official life in 2020), so we have never tested it on Python 3.5.   There's not much Python code in this package so you might be able to get it to work under 3.5 with a few tweaks; the error you see is because `README.rst` contains unicode characters to spell Zoltán's name correctly.

**Comment by cmbailey87** [comment]
thank you, I the support was for 3.6 and up on the SnapPy page.
thanks, 
using older version of SnapPy has got us by so far.
